spring.application.name=catalog

server.port=8080

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/catalog_db}

#spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST:localhost}
#spring.data.mongodb.port=${SPRING_DATA_MONGODB_PORT:27017}
#spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:catalog_db}
#spring.data.mongodb.username=${SPRING_DATA_MONGODB_USERNAME:}
#spring.data.mongodb.password=${SPRING_DATA_MONGODB_PASSWORD:}

logging.level.org.springframework.data.mongodb=INFO
logging.level.web=INFO
