spring.application.name=catalog
server.port=8080

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Force Mongo Auto-Configuration to resolve properties from the environment variables directly
#spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST:catalog-db}
#spring.data.mongodb.port=${SPRING_DATA_MONGODB_PORT:27017}
#spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:catalog_db}
#spring.data.mongodb.username=${SPRING_DATA_MONGODB_USERNAME:admin}
#spring.data.mongodb.password=${SPRING_DATA_MONGODB_PASSWORD:password}