apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: tiagofxbda/catalog-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: retail-config
                  key: MONGO_USER
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: retail-config
                  key: MONGO_HOST
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: retail-config
                  key: MONGO_DB
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: retail-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@$(MONGO_HOST):27017/$(MONGO_DB)"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: default
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
