apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - postgres.yaml
  - mongo.yaml
  - kafka.yaml
  - catalog-service.yaml
  - order-service.yaml

secretGenerator:
  - name: retail-secrets
    envs:
      - .env