spring.application.name=order
catalog.service.url=http://localhost:8081
spring.cloud.discovery.enabled=false
spring.coud.discovery.simple.enabled=false
debug=true
logging.level.org.springframework=DEBUG
spring.datasource.url=jdbc:h2:mem:order_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database.platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration,org.springframework.boot.autoconfigure.jpa.HibernateJpaAutoConfiguration
spring.main.allow-bean-definition-overriding=true
catalog.service.url=http://localhost:8081
#Disable Spring Cloud Service Discovery for tests
spring.cloud.discovery.enabled=false
spring.ccloud.simple.discovery.enabled=false
spring.autoconfigure.exclude=org.springframework.cloud.client.discovery.simple.SimpleDiscoveryClientAutoConfiguration
logging.level.org.springframework.beans.factory=DEBUG
logging.level.org.springframework.cloud.openfeign=TRACE
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer